[package]
name = "sniper"
version = "0.0.1"
authors = ["okanon <flat.cydia37jins.pc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
